import { icons } from "../../constants";

const questions = [
  {
    question: "What are your greatest strengths?",
    answer: "Tailor your strengths to the role, provide examples, and highlight problem-solving or leadership.",
    color: "#FFCDD2",
    icon: icons.question,
  },
  {
    question: "Why do you want to work here?",
    answer: "Research the company, connect your goals with their mission, and show genuine interest.",
    color: "#BBDEFB",
    icon: icons.question,
  },
  {
    question: "Describe a time you overcame a challenge.",
    answer: "Use the STAR method: Situation, Task, Action, and Result. Be concise and specific.",
    color: "#C8E6C9",
    icon: icons.question,
  },
  {
    question: "Where do you see yourself in 5 years?",
    answer: "Focus on growth, alignment with the company’s goals, and how the role helps you achieve your aspirations.",
    color: "#FFF9C4",
    icon: icons.question,
  },
  {
    question: "Tell me about a time when you worked in a team.",
    answer: "Explain the situation, your role in the team, and how you contributed to the success of the project.",
    color: "#D1C4E9",
    icon: icons.question,
  },
  {
    question: "Why should we hire you?",
    answer: "Discuss your skills, experience, and how you can contribute to the success of the company.",
    color: "#FFEB3B",
    icon: icons.question,
  },
  {
    question: "What are your weaknesses?",
    answer: "Be honest but focus on how you are working to improve those weaknesses.",
    color: "#FFAB91",
    icon: icons.question,
  },
  {
    question: "How do you handle stressful situations?",
    answer: "Explain how you stay calm and focused, and give an example of how you managed a stressful situation.",
    color: "#B3E5FC",
    icon: icons.question,
  },
  {
    question: "What motivates you?",
    answer: "Share what drives you, whether it's solving problems, helping others, or achieving personal goals.",
    color: "#C8E6C9",
    icon: icons.question,
  },
  {
    question: "How do you prioritize your work?",
    answer: "Discuss your process for organizing tasks, setting deadlines, and staying on top of your workload.",
    color: "#FFCDD2",
    icon: icons.question,
  },
  {
    question: "Tell me about a time you disagreed with a decision.",
    answer: "Explain how you handled the disagreement professionally and worked towards a constructive solution.",
    color: "#BBDEFB",
    icon: icons.question,
  },
  {
    question: "What is your greatest achievement?",
    answer: "Talk about a specific achievement that demonstrates your skills, dedication, and impact.",
    color: "#FFF9C4",
    icon: icons.question,
  },
  {
    question: "Why do you want to leave your current job?",
    answer: "Discuss your desire for growth and new challenges, without speaking negatively about your current employer.",
    color: "#D1C4E9",
    icon: icons.question,
  },
  {
    question: "How do you stay up-to-date in your field?",
    answer: "Mention any industry news, professional development activities, or courses you are involved in.",
    color: "#FFEB3B",
    icon: icons.question,
  },
  {
    question: "What are your salary expectations?",
    answer: "Provide a range based on research for the role and your experience level.",
    color: "#FFAB91",
    icon: icons.question,
  },
  {
    question: "Tell me about a time you handled a difficult customer.",
    answer: "Explain the situation, how you stayed calm, and the resolution you provided.",
    color: "#B3E5FC",
    icon: icons.question,
  },
  {
    question: "How do you handle feedback?",
    answer: "Discuss how you receive feedback and use it as an opportunity for improvement.",
    color: "#C8E6C9",
    icon: icons.question,
  },
  {
    question: "Describe a time you failed.",
    answer: "Talk about what you learned from the failure and how it made you better in the future.",
    color: "#FFCDD2",
    icon: icons.question,
  },
  {
    question: "What are your long-term career goals?",
    answer: "Share your career aspirations and how you plan to achieve them.",
    color: "#BBDEFB",
    icon: icons.question,
  },
  {
    question: "How would your previous employer describe you?",
    answer: "Provide a few qualities that your previous employer valued in you, such as reliability or initiative.",
    color: "#C8E6C9",
    icon: icons.question,
  },
  {
    question: "What skills do you bring to this role?",
    answer: "List the skills that are most relevant to the role and provide examples of how you've applied them.",
    color: "#FFF9C4",
    icon: icons.question,
  },
  {
    question: "How do you handle conflict at work?",
    answer: "Explain how you approach conflict with a solution-oriented mindset, ensuring a positive outcome for everyone.",
    color: "#D1C4E9",
    icon: icons.question,
  },
  {
    question: "What type of work environment do you thrive in?",
    answer: "Discuss the aspects of a work environment that help you succeed, such as collaboration or autonomy.",
    color: "#FFEB3B",
    icon: icons.question,
  },
  {
    question: "Tell me about a time you went above and beyond.",
    answer: "Give an example of how you exceeded expectations, whether in customer service, meeting deadlines, or a team project.",
    color: "#FFAB91",
    icon: icons.question,
  },
  {
    question: "What are your hobbies and interests?",
    answer: "Share a few hobbies that reflect your personality and how they help you maintain balance in your life.",
    color: "#B3E5FC",
    icon: icons.question,
  },
  {
    question: "Why did you choose this career path?",
    answer: "Discuss what attracted you to this career and how it aligns with your interests and values.",
    color: "#C8E6C9",
    icon: icons.question,
  },
  {
    question: "How do you handle multiple projects at once?",
    answer: "Explain your time management skills and give an example of how you successfully handled several tasks at the same time.",
    color: "#FFCDD2",
    icon: icons.question,
  },
  {
    question: "What do you know about our company?",
    answer: "Research the company beforehand and mention specific details about its values, culture, and achievements.",
    color: "#BBDEFB",
    icon: icons.question,
  },
  {
    question: "Tell me about a time you showed leadership.",
    answer: "Share a situation where you took initiative, whether leading a team or making important decisions.",
    color: "#C8E6C9",
    icon: icons.question,
  },
  {
    question: "What would you do if you disagreed with your manager?",
    answer: "Explain how you would handle a disagreement respectfully and work towards a solution.",
    color: "#FFF9C4",
    icon: icons.question,
  },
  {
    question: "How do you measure success?",
    answer: "Define what success means to you and how you track your progress in achieving your goals.",
    color: "#D1C4E9",
    icon: icons.question,
  },
  {
    question: "What is your biggest professional accomplishment?",
    answer: "Discuss a significant achievement and explain how it had a positive impact on your work or the company.",
    color: "#FFEB3B",
    icon: icons.question,
  },
  {
    question: "How do you stay organized?",
    answer: "Share your methods for staying organized, such as using tools, setting priorities, and managing your time effectively.",
    color: "#FFAB91",
    icon: icons.question,
  },
  {
    question: "How would you handle a situation where your team is falling behind?",
    answer: "Explain how you would identify the issues, provide support, and keep the team motivated to catch up.",
    color: "#B3E5FC",
    icon: icons.question,
  },
  {
    question: "What makes you unique?",
    answer: "Identify qualities or experiences that set you apart from other candidates, such as skills, personality, or work ethic.",
    color: "#C8E6C9",
    icon: icons.question,
  },
  {
    question: "Do you have any questions for us?",
    answer: "Always prepare a few questions for the interviewer about the company culture, team dynamics, or next steps.",
    color: "#FFCDD2",
    icon: icons.question,
  },
];

export default questions;
